package io.tryvital.vitalsamsunghealth.model

internal enum class SamsungRecordType {
    ActiveCaloriesBurned,
    BasalMetabolicRate,
    BloodGlucose,
    BloodPressure,
    BodyFat,
    BodyTemperature,
    CervicalMucus,
    Distance,
    ElevationGained,
    ExerciseSession,
    FloorsClimbed,
    HeartRate,
    HeartRateVariabilityRmssd,
    Height,
    Hydration,
    IntermenstrualBleeding,
    MenstruationFlow,
    MenstruationPeriod,
    Nutrition,
    OvulationTest,
    OxygenSaturation,
    Power,
    RespiratoryRate,
    RestingHeartRate,
    SexualActivity,
    SleepSession,
    Speed,
    Steps,
    TotalCaloriesBurned,
    Vo2Max,
    Weight,
}
