name: Android CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lint

      - uses: yutailang0119/action-android-lint@v4
        with:
          report-path: build/reports/*.xml

      - name: Build with Gradle
        run: ./gradlew :VitalClient:testDebugUnitTest :VitalDevices:testDebugUnitTest :VitalHealthConnect:testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
