name: Android Release

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Publish locally
        run: doppler -p maven-central -c prod run -- ./gradlew publish
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - name: Upload
        run: doppler -p maven-central -c prod run -- ./gradlew jreleaserDeploy
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
